#!/usr/bin/env bash

source "$(dirname $(readlink -f "$0"))"/util.sh

INPUT="$(input 1)"

function first_part() {
	local output=0

	while read -r mass; do
		(( output += $(getFuel "${mass}") ))
	done <<< "${INPUT}"

	first "${output}"
}

function second_part() {
	local output=0

	while read -r mass; do
		local current_mass="${mass}"
		local current_mass_fuel=0
		while [ "${current_mass}" -gt 0 ] ; do
			(( current_fuel = $(getFuel "${current_mass}") ))
			[ "${current_fuel}" -lt 1 ] && break
			(( current_mass_fuel += current_fuel ))
			(( current_mass = current_fuel ))
		done
		(( output += current_mass_fuel ))
	done <<< "${INPUT}"

	second "${output}"
}

function getFuel() {
	(( result = (($1 / 3) - 2) ))
	echo "${result}"
}

first_part
second_part
