#!/usr/bin/env bash

source "$(dirname $(readlink -f "$0"))"/util.sh

declare -a INPUT

ADD=1
MULTIPLY=2
HALT=99

EXPECTED_RESULT=19690720

function process_array() {
	local index=0
	while [ "${index}" -lt "${#INPUT[@]}" ]; do
		[ "${INPUT[${index}]}" -eq "${HALT}" ] && break
		process_code "${index}"
		(( index += 4 ))
	done
}

function process_code() {
	local first_index=${INPUT[(( $1 + 1 ))]}
	local first_value=${INPUT[${first_index}]}

	local second_index=${INPUT[(( $1 + 2 ))]}
	local second_value=${INPUT[${second_index}]}

	local position=${INPUT[(( $1 + 3))]}

	if [ "${INPUT[$1]}" -eq "${ADD}" ]; then
		(( sum = first_value + second_value ))
		INPUT[${position}]="${sum}"
	elif [ "${INPUT[$1]}" -eq "${MULTIPLY}" ]; then
		(( sum = first_value * second_value ))
		INPUT[${position}]="${sum}"
	else
		echo "Something went wrong my friend, got ${INPUT[$1]}"
	fi
}

function first_part() {
	IFS="," read -ra INPUT <<< "$(input 2)"

	INPUT[1]=12
	INPUT[2]=2

	process_array
	first "${INPUT[0]}"
}

function second_part() {
	for noun in {0..99}; do
		for verb in {0..99}; do
			IFS="," read -ra INPUT <<< "$(input 2)"
			INPUT[1]="${noun}"
			INPUT[2]="${verb}"
			process_array
			[[ ! "${INPUT[0]}" == "1969"* ]] && continue 2
			[ "${INPUT[0]}" = ${EXPECTED_RESULT} ] && break 2
		done
	done
	second "$(( noun * 100 + verb ))"
}

first_part
second_part
